#!/bin/bash

# This script sets up and starts the development environment.
# It dynamically creates or updates the .env file with the correct user and
# group IDs to ensure container permissions are set correctly.

set -e

ENV_FILE=".env"

# --- Dynamic .env file handling ---
if [ ! -f "$ENV_FILE" ]; then
    echo "Creating .env file..."

    # Get the Group ID (GID) for the 'docker' group on the host.
    if getent group docker > /dev/null; then
        DOCKER_GID=$(getent group docker | cut -d: -f3)
    else
        echo "Warning: 'docker' group not found on host. Using default GID 999."
        DOCKER_GID=999
    fi

    # Write all necessary variables to the .env file.
    {
        echo "# This file is auto-generated by start-dev.sh"
        echo "DOCKER_GID=${DOCKER_GID}"
        echo "USER_UID=$(id -u)"
        echo "USER_GID=$(id -g)"
        echo "# Add other environment variables below if needed"
        echo "POSTGRES_PASSWORD=defaultpassword"
    } > "$ENV_FILE"

    echo ".env file created successfully."
else
    echo ".env file already exists. Verifying contents..."

    # Check for DOCKER_GID and add if missing.
    if ! grep -q "^DOCKER_GID=" "$ENV_FILE"; then
        echo "DOCKER_GID not found. Appending..."
        if getent group docker > /dev/null; then
            DOCKER_GID=$(getent group docker | cut -d: -f3)
            echo "" >> "$ENV_FILE" # Add a newline for better formatting
            echo "DOCKER_GID=${DOCKER_GID}" >> "$ENV_FILE"
        else
            echo "Warning: 'docker' group not found on host. Can't add DOCKER_GID."
        fi
    fi

    # Check for USER_UID and add if missing.
    if ! grep -q "^USER_UID=" "$ENV_FILE"; then
        echo "USER_UID not found. Appending..."
        echo "" >> "$ENV_FILE"
        echo "USER_UID=$(id -u)" >> "$ENV_FILE"
    fi

    # Check for USER_GID and add if missing.
    if ! grep -q "^USER_GID=" "$ENV_FILE"; then
        echo "USER_GID not found. Appending..."
        echo "" >> "$ENV_FILE"
        echo "USER_GID=$(id -g)" >> "$ENV_FILE"
    fi
fi
